'use client'

import './globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {SolanaProvider} from '@/components/solana/solana-provider'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'

// Move static data outside component
const metadata = {
  title: 'stablesfun',
  description: 'Generated by create-solana-dapp',
}

const links = [
   { label: 'Account', path: '/account' },
] 

// Create a separate Provider wrapper to avoid re-mounting providers
function Providers({ children }: { children: React.ReactNode }) {
  return (
    <ReactQueryProvider>
      <ClusterProvider>
        <SolanaProvider>
          {children}
        </SolanaProvider>
      </ClusterProvider>
    </ReactQueryProvider>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <UiLayout links={links}>{children}</UiLayout>
        </Providers>
      </body>
    </html>
  )
}
